int8 force    # Percentage points of the gripper's max. gripping force.
              # Tolerated values in [50, 100]

bool use_gpe  # Whether to activate grip force and position maintenance.
              # Will only be used when available in the gripper.
              # Defaults to False.

bool outward  # Whether to open the gripper for grasping.
              # Defaults to False.

int16 velocity # Optional speed for the gripping motion (e.g., SoftGrip modes).
              # Defaults to 0.
---
bool success
string message
